

class Solution {
public:
    char findTheDifference(string s, string t) 
    {
        int ans=0;
        for(auto &x: t)
            ans+=x;                          //int+char=>int+ASCII of char
        for (auto &x: s)
            ans-=x;
        return char(ans);                    //converting ASCII to char
     }
};


/*
You are given two strings s and t.
String t is generated by random shuffling string s and then add one more letter at a random position.
Return the letter that was added to t.
Example 1:

Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.
*/